apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-app
  labels:
    app: argocd-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-demo-app
  template:
    metadata:
      labels:
        app: argocd-demo-app
    spec:
      containers:
      - name: argocd-demo-app
        image: atul0605/argocd-demo-app:12a0a6d6d3ad7cadece5cec2016ba9e6609423a7
        ports:
        - containerPort: 80
