apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-app
  labels:
    app: argocd-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-demo-app
  template:
    metadata:
      labels:
        app: argocd-demo-app
    spec:
      containers:
      - name: argocd-demo-app
        image: atul0605/argocd-demo-app:1296fb1728bf3fe1c6486d1b6690719e44b47677
        ports:
        - containerPort: 80
