apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-app
  labels:
    app: argocd-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-demo-app
  template:
    metadata:
      labels:
        app: argocd-demo-app
    spec:
      containers:
      - name: argocd-demo-app
        image: atul0605/argocd-demo-app:624ef967b61bbb656275f33c8d509885d975d78b
        ports:
        - containerPort: 80
